In [269]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

In [270]:
scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']

In [271]:
credentials = ServiceAccountCredentials.from_json_keyfile_name('SWOO-Analytics-BQ-ef3ef3805865.json', scope)

gc = gspread.authorize(credentials)

In [272]:
gc = gspread.authorize(credentials)

In [273]:
file = gc.open("Swooperstar Game Config")

In [274]:
file

In [275]:
worksheet = file.get_worksheet(1)

In [276]:
worksheet

In [277]:
import pandas as pd
df = pd.DataFrame(worksheet.get_all_values())

In [278]:
df = df.head(40)

In [279]:
df = df.drop(df.index[21])

In [280]:
df.reset_index(inplace = True)

In [281]:
df = df.drop('index',axis = 1)

In [282]:
#df

In [283]:
df1 = df.T

In [284]:
header = df1.iloc[0]

In [285]:
headers = []
for i in header:
    headers.append(i.replace(' ','_'))

In [286]:
type(header)

pandas.core.series.Series

In [287]:
headers = pd.Series( (v for v in headers) )

In [288]:
#headers

In [289]:
df1 = df1[1:]

In [290]:
df1 = df1.rename(columns = headers)

In [291]:
df1 = df1.drop('GameID',axis = 1)

In [292]:
df1

,Show_Date,Show_Time_(GST),Submission_Start_Time_(GST),Submission_End_Time_(GST),Video_Admin_Submission_Time,Theme,Game_Landing_Page_text_(Cash),Game_Landing_Page_text_(Lives),Script_1,Script_2,...,Shortlist_1_Entry_ID,Shortlist_2,Shortlist_3,Shortlist_4,Shortlist_5,Shortlist_6,Shortlist_7,Shortlist_8,Shortlist_9,Shortlist_10
1,16 Nov,18:30,,,,Talent,Tap to submit your video.\nRecord a 30-sec vid...,Watch the show on Fridays at the set time.\nBr...,Do the iconic scene of “Sharukh Khan” opening ...,Sing a song. For example: “Senorita” with guit...,...,shah19,tuku3,manpreetmannii,manutheemo007,madhusmitadash21,Dr_Dancer_,anushkayadavmeerut,rahulkhushlani,arpit_dadhich,ZohraHashmi
2,21 Nov,18:30,,,,Talent,Same as earlier,Same as earlier,Sing: Any song of your choice.,Dance on any song of your choice. Note: Play t...,...,-,-,-,-,-,-,-,-,-,-
3,23 Nov,18:30,,,,Talent,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Sing: Any song of your choice.,Dance on any song of your choice. Note: Play t...,...,prodPub121704161542822744432,prodPub122738521542805700372,prodPub83334801542542232450,prodPub00000001542895937623,prodPub00000001542895976826,prodPub00000001542896026637,prodPub00000001542896062006,prodPub00000001542896124249,prodPub00000001542896334618,prodPub00000001542895898727
4,25 Nov,18:30,23 Nov 11:00 AM,25 Nov 5:00 PM,,Singing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Sing a duet song with your partner,Sing a karaoke,...,prodPub126441651542766550061,prodPub104653411542824038625,prodPub70213751543136962752,prodPub00000001543137527183,prodPub00000001543137660564,prodPub00000001543137727716,prodPub00000001543137769633,prodPub00000001543137816573,prodPub00000001543141252643,prodPub91388541543144712662
5,27 Nov,18:30,25 Nov 3:00 PM,27 Nov 5:00 PM,,Dancing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Good In dancing ! Show us your moves on any so...,"Couple dance, we are Interested !! Bring It.",...,prodPub71928591543135077089,prodPub98626861543147022642,prodPub127108461543146928074,prodPub00000001543319057033,prodPub00000001543320476408,prodPub00000001543320521534,prodPub00000001543320557303,prodPub00000001543320594368,prodPub00000001543321317586,prodPub00000001543321495927
6,29 Nov,18:30,27 Nov 3:00 PM,29 Nov 5:00 PM,,Music Instrument,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,"In Love with your Music Intruments, play anyth...",Create music with any instrument you know,...,prodPub124528141542782705354,prodPub98849481543374962213,prodPub93018861542811810693,prodPub115694841542824936034,prodPub126769491542812369482,prodPub118553171543343400654,prodPub107150991543306870512,prodPub00000001543493187402,prodPub00000001543494123898,prodPub00000001543494389903
7,30 Nov,18:30,29 Nov 3:00 PM,30 Nov 5:00 PM,,Comedy/Mimic,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Making others laugh is a difficult process are...,Act on any comedy scene of your choice.,...,prodPub00000001543570109380,prodPub00000001543570214447,prodPub00000001543570332204,prodPub00000001543570405980,prodPub00000001543570470822,prodPub00000001543570545354,prodPub00000001543570624553,prodPub00000001543570686041,prodPub00000001543570824297,prodPub00000001543570895732
8,5 Dec,18:30,30 Nov 3:00 PM,5 Dec 5:00 PM,,Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,"Dance, Just Dance",Bollywood is what we Like !! Dance on any song...,...,prodPub129206981543409968491,prodPub00000001543998020101,prodPub00000001543997974757,prodPub00000001543997942921,prodPub00000001543997890450,prodPub00000001543997802059,prodPub00000001543997753229,prodPub00000001543997708957,prodPub00000001543997657163,prodPub00000001543997598197
9,6 Dec,18:30,5 Dec 3:00 PM,6 Dec 5:00 PM,,Singing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,"Become Swooperstar In Singing, Sing a song Of ...","Bathroom Singer, Its Okay. Sing for Us too",...,prodPub128296691543168267793,prodPub90829171544032632695,prodPub114438661543146720154,prodPub88243971544032837431,prodPub98887391544032266205,prodPub70213751544066053931,prodPub66284181544025567108,prodPub127670501543159270719,prodPub90899161544025684412,prodPub25892201544066283487
10,7 Dec,18:30,6 Dec 3:00 PM,7 Dec 5:00 PM,,Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Dance on Dilbar Song,"Dilbar Dilbar, hosh na khabar hai yeh kaisa as...",...,,prodPub89452971543751646507,,,prodPub91388541543323646491,,,prodPub129274671543318074291,,prodPub79770651544166710734
11,8 Dec,18:30,7 Dec 3:00 PM,8 Dec 5:00 PM,,Comedy,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Making others laugh is a difficult process are...,Act on any comedy scene of your choice.,...,,,,,,,prodPub127793271543744918604,,,
12,9 Dec,18:30,8 Dec 3:00 PM,9 Dec 5:00 PM,,Instruments,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,"In Love with your Music Intruments, play anyth...",Create music with any instrument you know,...,prodPub119073621544334714994,prodPub112782221544327790110,,prodPub112787111543419632115,prodPub113787641543398391215,prodPub134819771544340331690,prodPub115694841544293289337,prodPub135274091544340651720,prodPub125246341544195873437,
13,10 Dec,20:30,9 Dec 3:00 PM,10 Dec 5:00 PM,,Singing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,"Become Swooperstar In Singing, Sing a song Of ...","Bathroom Singer, Its Okay. Sing for Us too",...,prodPub119450361544427329827,,prodPub121452461544375812283,prodPub97892411544433452924,,prodPub104035341544422183674,,prodPub65920041544370242354,,prodPub67218721544427805657
14,11 Dec,18:30,10 Dec 3:00 PM,11 Dec 6:30 PM,,Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Dance on any Old Bollywood Songs 80's-90's,"OLD is GOLD, chose any old Songs and dance",...,,prodPub125246341544171774369,prodPub362511544242985269,,prodPub129726321544524704937,,,,,
15,12 Dec,18:30,11 Dec 4:30 PM,12 Dec 6:30 PM,,Acting,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,prodPub83853831544553472966,,prodPub110734201544591038342,,,,,,
16,13 Dec,18:30,12 Dec 4:30 PM,13 Dec 6:30 PM,,Instruments,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Play Tujhe dekha toh yeh jana sanam on any Ins...,"Girls Like SRK, DDLJ and Guitar",...,,,,,,,,,,
17,14 Dec,18:30,13 Dec 4:30 PM,14 Dec 6:30 PM,,Singing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Lag Ja Gale Ki Phir Ye Hasin Raat Ho Na Ho\nSh...,Sing Lag jaa Gale in your own voice let's see ...,...,,prodPub89469641544425410368,,,,,,,,
18,15 Dec,18:30,14 Dec 4:30 PM,15 Dec 6:30 PM,,Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Dance only on punjabi tracks,केवल पंजाबी गाने,...,,,,,,,,,,
19,16 Dec,18:30,15 Dec 4:30 PM,16 Dec 6:30 PM,,Acting,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,,,,,,,,,
20,17 Dec,18:30,16 Dec 4:30 PM,17 Dec 6:30 PM,,Comedy,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Making others laugh is a difficult process are...,Act on any comedy scene of your choice.,...,,,,,,,,,,
21,18 Dec,18:30,17 Dec 4:30 PM,18 Dec 6:30 PM,,Singing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,"Become Swooperstar In Singing, Sing a song Of ...","Bathroom Singer, Its Okay. Sing for Us too",...,,,,,,,,,,
22,19 Dec,18:30,18 Dec 4:30 PM,19 Dec 6:30 PM,,Instruments,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,"In Love with your Music Intruments, play anyth...",Create music with any instrument you know,...,,,,,,,,,,
23,20 Dec,18:30,19 Dec 4:30 PM,20 Dec 6:30 PM,,Specific Singing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Sing this Song 'Hai apna dil toh awaara',"इस गाने को गाओ\n'है अपना दिल तो आवारा, न जाने ...",...,,,,,,,,,,
24,20 Dec,21:30,20 Dec 4:30 PM,20 Dec 6:30 PM,,Specific Singing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Sing this Song 'Hai apna dil toh awaara',"इस गाने को गाओ\n'है अपना दिल तो आवारा, न जाने ...",...,,,,,,,,,,
25,21 Dec,18:30,20 Dec 4:30 PM,21 Dec 9:30 PM,,Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Dandiya Songs Only,Kem cho? Majama ne? If yes send a Gujrati dance,...,,,,,,,,,,
26,21 Dec,21:30,20 Dec 4:30 PM,21 Dec 9:30 PM,,Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Dandiya Songs Only,Kem cho? Majama ne? If yes send a Gujrati dance,...,,,,,,,,,,
27,22 Dec,18:30,21 Dec 7:30 PM,22 Dec 9:30 PM,,Child Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,We want to see how good your Children are tell...,Children Dance Only,...,,,,,,,,,,
28,22 Dec,21:30,21 Dec 7:30 PM,22 Dec 9:30 PM,,Child Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,We want to see how good your Children are tell...,Children Dance Only,...,,,,,,,,,,
29,23 Dec,18:30,22 Dec 7:30 PM,23 Dec 6:30 PM,,Acting/Mimic,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,,,,,,,,,
30,23 Dec,21:30,22 Dec 7:30 PM,23 Dec 6:30 PM,,Acting/Mimic,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,22 Mar,,,,,Singing,,,"Become Swooperstar In Singing, Sing a song Of ...","Bathroom Singer, Its Okay. Sing for Us too But...",...,,,,,,,,,,
205,22 Mar,,,,,Singing,Upload a 30 second clip of your best video. If...,,"Become Swooperstar In Singing, Sing a song Of ...","Bathroom Singer, Its Okay. Sing for Us too But...",...,,,,,,,,,,
206,23 Mar,,,,,Comedy,,,Making others laugh is a difficult process are...,Act on any comedy scene of your choice.,...,,,,,,,,,,
207,23 Mar,,,,,Comedy,,,Making others laugh is a difficult process are...,Act on any comedy scene of your choice.,...,,,,,,,,,,
208,24 Mar,,,,,Acting,,,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,,,,,,,,,
209,24 Mar,,,,,Acting,,,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,,,,,,,,,
210,25 Mar,,,,,Theme anchoring,,,"Act Like Niel, Naufa and host a show","You Like anchoring, show us your skills in Anc...",...,,,,,,,,,,
211,25 Mar,,,,,Theme anchoring,,,"Act Like Niel, Naufa and host a show","You Like anchoring, show us your skills in Anc...",...,,,,,,,,,,
212,26 Mar,,,,,Instruments,,,"In Love with your Music Intruments, play anyth...",Create music with any instrument you know,...,,,,,,,,,,
213,26 Mar,,,,,Instruments,,,"In Love with your Music Intruments, play anyth...",Create music with any instrument you know,...,,,,,,,,,,
214,27 Mar,,,,,Specific Dance,,,"Dance, Just Dance",Bollywood is what we Like !! Dance on any song...,...,,,,,,,,,,
215,27 Mar,,,,,Specific Dance,,,"Dance, Just Dance",Bollywood is what we Like !! Dance on any song...,...,,,,,,,,,,
216,28 Mar,,,,,Comedy,,,Making others laugh is a difficult process are...,Act on any comedy scene of your choice.,...,,,,,,,,,,
217,28 Mar,,,,,Comedy,,,Making others laugh is a difficult process are...,Act on any comedy scene of your choice.,...,,,,,,,,,,
218,29 Mar,,,,,Acting,,,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,,,,,,,,,
219,29 Mar,,,,,Acting,,,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,,,,,,,,,
220,30 Mar,,,,,,,,,,...,,,,,,,,,,
221,30 Mar,,,,,,,,,,...,,,,,,,,,,
222,31 Mar,,,,,,,,,,...,,,,,,,,,,
223,31 Mar,,,,,,,,,,...,,,,,,,,,,
224,1 Apr,,,,,,,,,,...,,,,,,,,,,
225,1 Apr,,,,,,,,,,...,,,,,,,,,,
226,2 Apr,,,,,,,,,,...,,,,,,,,,,
227,2 Apr,,,,,,,,,,...,,,,,,,,,,
228,3 Apr,,,,,,,,,,...,,,,,,,,,,
229,3 Apr,,,,,,,,,,...,,,,,,,,,,
230,4 Apr,,,,,,,,,,...,,,,,,,,,,
231,4 Apr,,,,,,,,,,...,,,,,,,,,,
232,5 Apr,,,,,,,,,,...,,,,,,,,,,
233,5 Apr,,,,,,,,,,...,,,,,,,,,,

In [293]:
headers

0                                Show_Date
1                          Show_Time_(GST)
2              Submission_Start_Time_(GST)
3                Submission_End_Time_(GST)
4              Video_Admin_Submission_Time
5                                   GameID
6                                    Theme
7            Game_Landing_Page_text_(Cash)
8           Game_Landing_Page_text_(Lives)
9                                 Script_1
10                                Script_2
11                                Script_3
12                                Script_4
13                                Script_5
14                               FAQ_video
15                        Host_Intro_video
16                                  Winner
17                           Prize_money_1
18                           Prize_money_2
19                           Prize_money_3
20                    Prize_money_for_4-10
21    Total_Videos_to_be_selected_for_show
22                    Length_of_each_video
23                        Timer_for_judges
24                             Life/Winner
25                              Video_File
26        Length_of_background_video_(sec)
27        Length_of_background_video_(min)
28                                 Country
29                    Shortlist_1_Entry_ID
30                             Shortlist_2
31                             Shortlist_3
32                             Shortlist_4
33                             Shortlist_5
34                             Shortlist_6
35                             Shortlist_7
36                             Shortlist_8
37                             Shortlist_9
38                            Shortlist_10
dtype: object

In [294]:
df1 = df1.rename(columns = {'Show_Time_(GST)':'Show_Time_in_GST','Submission_Start_Time_(GST)':'Submission_Start_Time_in_GST',
                            
                            'Submission_End_Time_(GST)':'Submission_End_Time_in_GST','Game_Landing_Page_text_(Cash)':'Game_Landing_Page_text_Cash',
                            
                            'Game_Landing_Page_text_(Lives)':'Game_Landing_Page_text_Lives','Length_of_background_video_(sec)':'Length_of_background_video_in_seconds',
                            
                            'Length_of_background_video_(min)':'Length_of_background_video_in_minutes','Prize_money_for_4-10':'Prize_money_for_4_to_10',
                             
                            'Life/Winner':'Life_or_Winner'})

In [295]:
df1

,Show_Date,Show_Time_in_GST,Submission_Start_Time_in_GST,Submission_End_Time_in_GST,Video_Admin_Submission_Time,Theme,Game_Landing_Page_text_Cash,Game_Landing_Page_text_Lives,Script_1,Script_2,...,Shortlist_1_Entry_ID,Shortlist_2,Shortlist_3,Shortlist_4,Shortlist_5,Shortlist_6,Shortlist_7,Shortlist_8,Shortlist_9,Shortlist_10
1,16 Nov,18:30,,,,Talent,Tap to submit your video.\nRecord a 30-sec vid...,Watch the show on Fridays at the set time.\nBr...,Do the iconic scene of “Sharukh Khan” opening ...,Sing a song. For example: “Senorita” with guit...,...,shah19,tuku3,manpreetmannii,manutheemo007,madhusmitadash21,Dr_Dancer_,anushkayadavmeerut,rahulkhushlani,arpit_dadhich,ZohraHashmi
2,21 Nov,18:30,,,,Talent,Same as earlier,Same as earlier,Sing: Any song of your choice.,Dance on any song of your choice. Note: Play t...,...,-,-,-,-,-,-,-,-,-,-
3,23 Nov,18:30,,,,Talent,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Sing: Any song of your choice.,Dance on any song of your choice. Note: Play t...,...,prodPub121704161542822744432,prodPub122738521542805700372,prodPub83334801542542232450,prodPub00000001542895937623,prodPub00000001542895976826,prodPub00000001542896026637,prodPub00000001542896062006,prodPub00000001542896124249,prodPub00000001542896334618,prodPub00000001542895898727
4,25 Nov,18:30,23 Nov 11:00 AM,25 Nov 5:00 PM,,Singing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Sing a duet song with your partner,Sing a karaoke,...,prodPub126441651542766550061,prodPub104653411542824038625,prodPub70213751543136962752,prodPub00000001543137527183,prodPub00000001543137660564,prodPub00000001543137727716,prodPub00000001543137769633,prodPub00000001543137816573,prodPub00000001543141252643,prodPub91388541543144712662
5,27 Nov,18:30,25 Nov 3:00 PM,27 Nov 5:00 PM,,Dancing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Good In dancing ! Show us your moves on any so...,"Couple dance, we are Interested !! Bring It.",...,prodPub71928591543135077089,prodPub98626861543147022642,prodPub127108461543146928074,prodPub00000001543319057033,prodPub00000001543320476408,prodPub00000001543320521534,prodPub00000001543320557303,prodPub00000001543320594368,prodPub00000001543321317586,prodPub00000001543321495927
6,29 Nov,18:30,27 Nov 3:00 PM,29 Nov 5:00 PM,,Music Instrument,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,"In Love with your Music Intruments, play anyth...",Create music with any instrument you know,...,prodPub124528141542782705354,prodPub98849481543374962213,prodPub93018861542811810693,prodPub115694841542824936034,prodPub126769491542812369482,prodPub118553171543343400654,prodPub107150991543306870512,prodPub00000001543493187402,prodPub00000001543494123898,prodPub00000001543494389903
7,30 Nov,18:30,29 Nov 3:00 PM,30 Nov 5:00 PM,,Comedy/Mimic,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Making others laugh is a difficult process are...,Act on any comedy scene of your choice.,...,prodPub00000001543570109380,prodPub00000001543570214447,prodPub00000001543570332204,prodPub00000001543570405980,prodPub00000001543570470822,prodPub00000001543570545354,prodPub00000001543570624553,prodPub00000001543570686041,prodPub00000001543570824297,prodPub00000001543570895732
8,5 Dec,18:30,30 Nov 3:00 PM,5 Dec 5:00 PM,,Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,"Dance, Just Dance",Bollywood is what we Like !! Dance on any song...,...,prodPub129206981543409968491,prodPub00000001543998020101,prodPub00000001543997974757,prodPub00000001543997942921,prodPub00000001543997890450,prodPub00000001543997802059,prodPub00000001543997753229,prodPub00000001543997708957,prodPub00000001543997657163,prodPub00000001543997598197
9,6 Dec,18:30,5 Dec 3:00 PM,6 Dec 5:00 PM,,Singing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,"Become Swooperstar In Singing, Sing a song Of ...","Bathroom Singer, Its Okay. Sing for Us too",...,prodPub128296691543168267793,prodPub90829171544032632695,prodPub114438661543146720154,prodPub88243971544032837431,prodPub98887391544032266205,prodPub70213751544066053931,prodPub66284181544025567108,prodPub127670501543159270719,prodPub90899161544025684412,prodPub25892201544066283487
10,7 Dec,18:30,6 Dec 3:00 PM,7 Dec 5:00 PM,,Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Dance on Dilbar Song,"Dilbar Dilbar, hosh na khabar hai yeh kaisa as...",...,,prodPub89452971543751646507,,,prodPub91388541543323646491,,,prodPub129274671543318074291,,prodPub79770651544166710734
11,8 Dec,18:30,7 Dec 3:00 PM,8 Dec 5:00 PM,,Comedy,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Making others laugh is a difficult process are...,Act on any comedy scene of your choice.,...,,,,,,,prodPub127793271543744918604,,,
12,9 Dec,18:30,8 Dec 3:00 PM,9 Dec 5:00 PM,,Instruments,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,"In Love with your Music Intruments, play anyth...",Create music with any instrument you know,...,prodPub119073621544334714994,prodPub112782221544327790110,,prodPub112787111543419632115,prodPub113787641543398391215,prodPub134819771544340331690,prodPub115694841544293289337,prodPub135274091544340651720,prodPub125246341544195873437,
13,10 Dec,20:30,9 Dec 3:00 PM,10 Dec 5:00 PM,,Singing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,"Become Swooperstar In Singing, Sing a song Of ...","Bathroom Singer, Its Okay. Sing for Us too",...,prodPub119450361544427329827,,prodPub121452461544375812283,prodPub97892411544433452924,,prodPub104035341544422183674,,prodPub65920041544370242354,,prodPub67218721544427805657
14,11 Dec,18:30,10 Dec 3:00 PM,11 Dec 6:30 PM,,Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Dance on any Old Bollywood Songs 80's-90's,"OLD is GOLD, chose any old Songs and dance",...,,prodPub125246341544171774369,prodPub362511544242985269,,prodPub129726321544524704937,,,,,
15,12 Dec,18:30,11 Dec 4:30 PM,12 Dec 6:30 PM,,Acting,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,prodPub83853831544553472966,,prodPub110734201544591038342,,,,,,
16,13 Dec,18:30,12 Dec 4:30 PM,13 Dec 6:30 PM,,Instruments,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Play Tujhe dekha toh yeh jana sanam on any Ins...,"Girls Like SRK, DDLJ and Guitar",...,,,,,,,,,,
17,14 Dec,18:30,13 Dec 4:30 PM,14 Dec 6:30 PM,,Singing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Lag Ja Gale Ki Phir Ye Hasin Raat Ho Na Ho\nSh...,Sing Lag jaa Gale in your own voice let's see ...,...,,prodPub89469641544425410368,,,,,,,,
18,15 Dec,18:30,14 Dec 4:30 PM,15 Dec 6:30 PM,,Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Dance only on punjabi tracks,केवल पंजाबी गाने,...,,,,,,,,,,
19,16 Dec,18:30,15 Dec 4:30 PM,16 Dec 6:30 PM,,Acting,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,,,,,,,,,
20,17 Dec,18:30,16 Dec 4:30 PM,17 Dec 6:30 PM,,Comedy,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Making others laugh is a difficult process are...,Act on any comedy scene of your choice.,...,,,,,,,,,,
21,18 Dec,18:30,17 Dec 4:30 PM,18 Dec 6:30 PM,,Singing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,"Become Swooperstar In Singing, Sing a song Of ...","Bathroom Singer, Its Okay. Sing for Us too",...,,,,,,,,,,
22,19 Dec,18:30,18 Dec 4:30 PM,19 Dec 6:30 PM,,Instruments,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,"In Love with your Music Intruments, play anyth...",Create music with any instrument you know,...,,,,,,,,,,
23,20 Dec,18:30,19 Dec 4:30 PM,20 Dec 6:30 PM,,Specific Singing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Sing this Song 'Hai apna dil toh awaara',"इस गाने को गाओ\n'है अपना दिल तो आवारा, न जाने ...",...,,,,,,,,,,
24,20 Dec,21:30,20 Dec 4:30 PM,20 Dec 6:30 PM,,Specific Singing,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Sing this Song 'Hai apna dil toh awaara',"इस गाने को गाओ\n'है अपना दिल तो आवारा, न जाने ...",...,,,,,,,,,,
25,21 Dec,18:30,20 Dec 4:30 PM,21 Dec 9:30 PM,,Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Dandiya Songs Only,Kem cho? Majama ne? If yes send a Gujrati dance,...,,,,,,,,,,
26,21 Dec,21:30,20 Dec 4:30 PM,21 Dec 9:30 PM,,Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Dandiya Songs Only,Kem cho? Majama ne? If yes send a Gujrati dance,...,,,,,,,,,,
27,22 Dec,18:30,21 Dec 7:30 PM,22 Dec 9:30 PM,,Child Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,We want to see how good your Children are tell...,Children Dance Only,...,,,,,,,,,,
28,22 Dec,21:30,21 Dec 7:30 PM,22 Dec 9:30 PM,,Child Dance,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,We want to see how good your Children are tell...,Children Dance Only,...,,,,,,,,,,
29,23 Dec,18:30,22 Dec 7:30 PM,23 Dec 6:30 PM,,Acting/Mimic,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,,,,,,,,,
30,23 Dec,21:30,22 Dec 7:30 PM,23 Dec 6:30 PM,,Acting/Mimic,Upload a 30 second clip of your best video. If...,View a collection of shortlisted videos on the...,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,22 Mar,,,,,Singing,,,"Become Swooperstar In Singing, Sing a song Of ...","Bathroom Singer, Its Okay. Sing for Us too But...",...,,,,,,,,,,
205,22 Mar,,,,,Singing,Upload a 30 second clip of your best video. If...,,"Become Swooperstar In Singing, Sing a song Of ...","Bathroom Singer, Its Okay. Sing for Us too But...",...,,,,,,,,,,
206,23 Mar,,,,,Comedy,,,Making others laugh is a difficult process are...,Act on any comedy scene of your choice.,...,,,,,,,,,,
207,23 Mar,,,,,Comedy,,,Making others laugh is a difficult process are...,Act on any comedy scene of your choice.,...,,,,,,,,,,
208,24 Mar,,,,,Acting,,,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,,,,,,,,,
209,24 Mar,,,,,Acting,,,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,,,,,,,,,
210,25 Mar,,,,,Theme anchoring,,,"Act Like Niel, Naufa and host a show","You Like anchoring, show us your skills in Anc...",...,,,,,,,,,,
211,25 Mar,,,,,Theme anchoring,,,"Act Like Niel, Naufa and host a show","You Like anchoring, show us your skills in Anc...",...,,,,,,,,,,
212,26 Mar,,,,,Instruments,,,"In Love with your Music Intruments, play anyth...",Create music with any instrument you know,...,,,,,,,,,,
213,26 Mar,,,,,Instruments,,,"In Love with your Music Intruments, play anyth...",Create music with any instrument you know,...,,,,,,,,,,
214,27 Mar,,,,,Specific Dance,,,"Dance, Just Dance",Bollywood is what we Like !! Dance on any song...,...,,,,,,,,,,
215,27 Mar,,,,,Specific Dance,,,"Dance, Just Dance",Bollywood is what we Like !! Dance on any song...,...,,,,,,,,,,
216,28 Mar,,,,,Comedy,,,Making others laugh is a difficult process are...,Act on any comedy scene of your choice.,...,,,,,,,,,,
217,28 Mar,,,,,Comedy,,,Making others laugh is a difficult process are...,Act on any comedy scene of your choice.,...,,,,,,,,,,
218,29 Mar,,,,,Acting,,,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,,,,,,,,,
219,29 Mar,,,,,Acting,,,Mimic Any Dialogue of Bollywood movie,Lip Sync on any dialogue or song of your choice,...,,,,,,,,,,
220,30 Mar,,,,,,,,,,...,,,,,,,,,,
221,30 Mar,,,,,,,,,,...,,,,,,,,,,
222,31 Mar,,,,,,,,,,...,,,,,,,,,,
223,31 Mar,,,,,,,,,,...,,,,,,,,,,
224,1 Apr,,,,,,,,,,...,,,,,,,,,,
225,1 Apr,,,,,,,,,,...,,,,,,,,,,
226,2 Apr,,,,,,,,,,...,,,,,,,,,,
227,2 Apr,,,,,,,,,,...,,,,,,,,,,
228,3 Apr,,,,,,,,,,...,,,,,,,,,,
229,3 Apr,,,,,,,,,,...,,,,,,,,,,
230,4 Apr,,,,,,,,,,...,,,,,,,,,,
231,4 Apr,,,,,,,,,,...,,,,,,,,,,
232,5 Apr,,,,,,,,,,...,,,,,,,,,,
233,5 Apr,,,,,,,,,,...,,,,,,,,,,

In [296]:
df1.to_gbq('swoo_gaming_service.Swooperstar_Config_Sheet', 
                 'swoo-analytics-bq',
                 chunksize=None, 
                 if_exists='replace',
                 verbose=False
                 )

/Users/yaswanth/anaconda3/lib/python3.7/site-packages/pandas_gbq/gbq.py:969: FutureWarning: verbose is deprecated and will be removed in a future version. Set logging level in order to vary verbosity
  stacklevel=1,
1it [00:07,  7.81s/it]